# -*- coding: utf-8 -*-
"""Bigbasket.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mklcp3N7wqi9UTag1os4bYqLcruUfWP6
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Importing the required libraries:
#pandas      : used to read,manipulate and handle missing values.
#Numpy       :It uses for numerical computing that provides efficient and fast operations on arrays  such as addition, subtraction, multiplication, and division.
#Matplotlib  :functions for creating different types of plots, including line plots, scatter plots, bar plots, histograms.
#seaborn     :It is a powerful tool for data exploration, allowing you to quickly visualize your data and identify patterns and trends.

"""Reading the dataset by using the pandas library and providing the encoding parameter as ISO-8859-1 which is used from encoding to decode the file's contents correctly.  """

data = pd.read_csv("/content/Big Basket Food Delivery.csv", encoding="ISO-8859-1")

"""The top three rows of the dataset"""

data.head(3)

data.tail(3)

data.size

data.shape

data.describe()

"""Finding the null values in the dataset"""

data.isna().sum()

#There  ia a null value prresent in the "Average Cost for two","Cuisines" and "Price range"

"""checking the data types of the dataset features"""

data.dtypes

data['City'].value_counts()

"""column names"""

data.columns

columns=['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes']

cat_col=['Restaurant Name','City','Address','Locality', 'Locality Verbose','Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range','Rating color', 'Rating text']

sns.countplot(data)
fig = plt.figure(figsize=(50,20))

"""splitting the data into x and y """

x=data.drop(["Aggregate rating"],axis=1)
y=data["Aggregate rating"]

fig, ax = plt.subplots(figsize=(15,15))
sns.heatmap(data.corr(),annot=True,cmap='Accent')

# There is a relationship between the "Aggregate rating" and "Votes" based on the no of the votes voted the aggregate rating of the restaurent

data["Cuisines"] = data["Cuisines"].fillna(data["Cuisines"].mode()[0])

data.isna().sum()

data["Cuisines"].mode()

data['Cuisines'].mode()[0]

for i in cat_col:
    data[i] = data[i].astype('category').cat.codes

data.dtypes

data["Average Cost for two"] = data["Average Cost for two"].fillna(data["Average Cost for two"].mean())
data["Price range"] = data["Price range"].fillna(data["Price range"].mean())

data.isna().sum()

# allthe null values in the dataset are filled

